import React from 'react';
import { RubricBars } from './RubricBars';
import { SampleQuestions } from './SampleQuestions';
import { Button } from './Button';
import { DownloadIcon, SparklesIcon, LoadingSpinner } from './icons';
import type { Lead, RubricItem, SampleQuestion } from '../types';

interface PreviewProps {
  lead: Lead;
  roleLabel: string;
  seniorityLabel: string;
  rubric: RubricItem[];
  sampleQuestions: SampleQuestion[];
  styles: Set<string>;
  onDownload: () => void;
  onGenerateQuestions: () => void;
  isGenerating: boolean;
  error: string | null;
}

const InfoPill: React.FC<{ children: React.ReactNode, className?: string }> = ({ children, className }) => (
    <span className={`inline-block bg-slate-800 text-slate-300 rounded-full px-3 py-1 text-sm font-medium border border-slate-700 ${className}`}>{children}</span>
);

export const Preview: React.FC<PreviewProps> = ({ lead, roleLabel, seniorityLabel, rubric, sampleQuestions, styles, onDownload, onGenerateQuestions, isGenerating, error }) => {
  return (
    <div className="sticky top-8 border border-blue-900/50 bg-gradient-to-br from-slate-900 to-slate-950 rounded-2xl p-5 space-y-5 print:border-none print:bg-white print:text-black print:shadow-none">
      <h3 className="text-xl font-semibold text-white print:text-black">Plan Preview</h3>
      
      {/* Header */}
      <div className="space-y-2 text-sm">
        <div className="flex flex-wrap gap-2 items-center"><strong className="w-20">Company:</strong> <InfoPill>{lead.company}</InfoPill></div>
        <div className="flex flex-wrap gap-2 items-center"><strong className="w-20">Contact:</strong> <InfoPill>{lead.name}</InfoPill> <InfoPill>{lead.email}</InfoPill></div>
        <div className="flex flex-wrap gap-2 items-center"><strong className="w-20">Role:</strong> <InfoPill>{roleLabel}</InfoPill></div>
        <div className="flex flex-wrap gap-2 items-center"><strong className="w-20">Seniority:</strong> <InfoPill>{seniorityLabel}</InfoPill></div>
      </div>
      
      <hr className="border-slate-800 print:hidden"/>

      {/* Rubric */}
      <div>
        <h4 className="font-semibold text-white print:text-black">Rubric Weights</h4>
        <p className="text-xs text-slate-400 print:hidden">Auto-generated by role & seniority. Edit skills to adjust.</p>
        <RubricBars rubric={rubric} />
      </div>

      <hr className="border-slate-800 print:hidden"/>

      {/* Questions */}
      <div>
        <div className="flex justify-between items-center">
            <h4 className="font-semibold text-white print:text-black">AI-Generated Sample Questions</h4>
             <div className="print:hidden">
                <Button onClick={onGenerateQuestions} disabled={isGenerating} size="sm" variant="secondary">
                    {isGenerating ? <LoadingSpinner /> : <SparklesIcon />}
                    {isGenerating ? 'Generating...' : 'Generate'}
                </Button>
            </div>
        </div>
        <SampleQuestions questions={sampleQuestions} isLoading={isGenerating} error={error}/>
      </div>

      <hr className="border-slate-800 print:hidden"/>

      {/* Styles */}
      <div>
        <h4 className="font-semibold text-white print:text-black mb-2">Selected Styles</h4>
        <div className="flex flex-wrap gap-2">
            {[...styles].length > 0 ? [...styles].map(s => <InfoPill key={s}>{s}</InfoPill>) : <InfoPill>—</InfoPill>}
        </div>
      </div>
      
      <hr className="border-slate-800 print:hidden"/>

      {/* CTA */}
      <div className="space-y-3 print:hidden">
        <Button onClick={onDownload} fullWidth>
          <DownloadIcon />
          Generate & Download PDF
        </Button>
        <a href="https://intervue.io/book-demo" target="_blank" rel="noopener noreferrer" className="block">
          <Button variant="secondary" fullWidth>
            Book a Demo with Intervue
          </Button>
        </a>
        <p className="text-xs text-slate-400 text-center">We'll ask for your name & email to add to the PDF header.</p>
      </div>
    </div>
  );
};